server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态路由
      routes:
        - id: payment-route1   #路由的ID，。没有固定要求，但要唯一
          uri: lb://CLOUD-PAYMENT-SERVICE    #从注册中心去动态路由
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
        - id: payment-route2
          uri: lb://CLOUD-PAYMENT-SERVICE
          #uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**

eureka:
  client:
    #表示是否将自己注册进eureka
    register-with-eureka: true
    #表示是否让eureka注册中心抓取自己信息，单点无所谓，集群必须是true
    fetch-registry: true
    service-url:
       defaultZone:  http://eureka7001.com:7001/eureka/
      #defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    hostname: cloud-gateway-service
