server:
  port: 80

#入住注册中心的服务名
spring:
  application:
    name: cloud-hystrix-order-service

eureka:
  client:
    #表示是否将自己注册进eureka
    register-with-eureka: true
    #表示是否让eureka注册中心抓取自己信息，单点无所谓，集群必须是true
    fetch-registry: true
    service-url:
       defaultZone:  http://localhost:7001/eureka/
#      defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
feign:
  hystrix:
    enabled: true