server:
  port: 8001

#入住注册中心的服务名
spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    #表示是否将自己注册进eureka
    register-with-eureka: true
    #表示是否让eureka注册中心抓取自己信息，单点无所谓，集群必须是true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/
#      defaultZone:  http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/  #集群版
  #更改服务在注册中心的status名字，方便运维调试区分
  instance:
    instance-id:  payment8001
    #在eureka监控网页鼠标放上去显示IP地址
    prefer-ip-address: true
    #客户端向服务端发送心跳的时间间隔，默认30秒
#    lease-renewal-interval-in-seconds: 30
#     服务端等待时间上限，超时将清除服务
#    lease-expiration-duration-in-seconds:
